### ISSUE TITLE
Instead of sorting alphabetically it'll be better to do sorting based on recent ones

### ISSUE THREAD

**Issue by divy221** [malgamves/CommunityWriterPrograms#188]
Currently, most of the companies in the repo are not accepting the new authors, still, they are in the repo. It'll be great if we can change the sorting order from alphabetically to the recent ones on the top. This will help authors quickly find recent and active programs.
For example, Abstract API, Agora, Adam the automater, etc. are not actively contacting authors but they are still on top and driving traffic to their website from this repo.

**Comment by karllhughes** [comment]
I think we should remove any that are no longer accepting applications, personally. We can always add them back when they open back up.

If you'd like, you could submit a PR removing any that aren't active.

**Comment by divy221** [comment]
Makes sense, Karl. I can create a PR draft for inactive ones, but few companies are doing this very cleverly. Despite their forms being open, they are not reaching out to authors or giving them any updates. I think mostly to drive traffic from this repo to their website.

Would love to hear your thoughts on sorting based on the recent programs.

**Comment by karllhughes** [comment]
I'm against sorting by recent just because it's less consistent. That said, I see the use case.

If we wanted to do something more advanced, we could build a little Github pages site that uses JS to sort or filter entries. We haven't done this because the list is relatively manageable and it would take more time than I have.

In the short term, users who want to keep up with the most recent programs can just watch this repo for changes. All new entries come in as PRs so it's pretty easy to see what's been added recently if you want to.

**Comment by divy221** [comment]
Great point, Karl! I am thinking to work on a page for this and having some sort of filters. Thanks for your input.
